### ISSUE TITLE
HttpRequestException

### ISSUE THREAD

**Issue by f-e-l-i-x** [jeremy-collette/lichess3d#9]
I am getting "Exception: System.Net.Http.HttpRequestException: 401 (Unauthorized)"
when starting the game

**Comment by jeremy-collette** [comment]
Hi @f-e-l-i-x ,

Can you please try the following:

1. Create a Lichess personal [API access token](https://lichess.org/account/oauth/token) and add permissions to "Play games with the board API". Save it somewhere safe.
2. Create a new Lichess game, and get the game ID from the URL (e.g. `https://lichess.org/GhZ4geRb` has the game ID `GhZ4geRb`)
3. Start lichess3d and paste the personal API access token in to the "Lichess API Key" field and the game ID in to the "Lichess Game ID" field.
4. Play chess!

Thanks

**Comment by f-e-l-i-x** [comment]
Thanks very much. You were right, I had given the token the wrong permissions.
